# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20170825_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='completed_levels',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
