# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level1', '0003_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='seq',
            new_name='sequence',
        ),
    ]
