# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level1', '0005_auto_20170825_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
