# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level1', '0006_auto_20170825_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='sequence',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
