# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level1', '0009_auto_20170828_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='sequence',
            field=models.CharField(blank=True, default="{1: ['4', '6', '7', '5'], 2: ['wr3', 'wr2', 'right', 'wr1']}", max_length=200),
        ),
    ]
