# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level1', '0010_auto_20170828_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='answered_questions',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='response',
            name='bookmarked_questions',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='response',
            name='sequence',
            field=models.CharField(blank=True, max_length=2500),
        ),
    ]
