# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level1', '0011_auto_20170828_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='negative_points',
            field=models.PositiveIntegerField(default=0, help_text='If you want to set -1 as negative points then enter 1 here'),
        ),
        migrations.AddField(
            model_name='question',
            name='point',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
