# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level1', '0012_auto_20170828_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='set',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=2),
        ),
    ]
