# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level1', '0013_question_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='description',
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
