# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level1', '0014_auto_20171002_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(max_length=1000),
        ),
    ]
