# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20170828_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='completed_levels',
            field=models.PositiveIntegerField(default=0, max_length=500),
        ),
    ]
