# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20170831_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='completed_levels',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
