# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level1', '0007_auto_20170826_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='answered_questions',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='response',
            name='bookmarked_questions',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='response',
            name='sequence',
            field=models.CharField(blank=True, default='1', max_length=200),
        ),
        migrations.AlterField(
            model_name='response',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
