# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level1', '0008_auto_20170826_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='sequence',
            field=models.CharField(blank=True, default='[2, 1]', max_length=200),
        ),
    ]
